### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by HanifWadowskyy** [KCodeYT/SkyBlockClone#1]
19:38:30 [ERROR] Catching                                                                      
java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils                                
        at ms.kevi.skyblock.level.LevelUtil.init(LevelUtil.java:63) ~[?:?]                     
        at ms.kevi.skyblock.SkyBlockPlugin.onLoad(SkyBlockPlugin.java:90) ~[?:?]               
        at cn.nukkit.plugin.JavaPluginLoader.initPlugin(JavaPluginLoader.java:112) ~[powernukki
t-1.6.0.0-PN-SNAPSHOT-shaded.jar:?]                                                            
        at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:60) ~[powernukkit
-1.6.0.0-PN-SNAPSHOT-shaded.jar:?]                                                             
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:123) ~[powernukkit-1.6.
0.0-PN-SNAPSHOT-shaded.jar:?]                                                                  
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:294) ~[powernukkit-1.6
.0.0-PN-SNAPSHOT-shaded.jar:?]                                                                 
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:160) ~[powernukkit-1.6
.0.0-PN-SNAPSHOT-shaded.jar:?]                                                                 
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:152) ~[powernukkit-1.6
.0.0-PN-SNAPSHOT-shaded.jar:?]                                                                 
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:148) ~[powernukkit-1.6
.0.0-PN-SNAPSHOT-shaded.jar:?]                                                                 
        at cn.nukkit.Server.<init>(Server.java:689) ~[powernukkit-1.6.0.0-PN-SNAPSHOT-shaded.ja
r:?]                                                                                           
        at cn.nukkit.Nukkit.main(Nukkit.java:200) [powernukkit-1.6.0.0-PN-SNAPSHOT-shaded.jar:?
]                                                                                              
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils                   
        at java.net.URLClassLoader.findClass(URLClassLoader.java:476) ~[?:?]                   
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:43) ~[powernukki
t-1.6.0.0-PN-SNAPSHOT-shaded.jar:?]                                                            
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:27) ~[powernukki
t-1.6.0.0-PN-SNAPSHOT-shaded.jar:?]                                                            
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]                        
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]                        
        ... 11 more                                                                            
19:38:30 [INFO ] Stopping other threads

**Comment by KCodeYT** [comment]
Thats caused because I currently dont shade dependencies into the plugin, im fixing that on another day

**Comment by KCodeYT** [comment]
Fixed in latest commit
